[package]
name = "fr24-detector"
version = "1.0.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.40.1", features = ["bundled"] }
json-escape = "0.3.1"

[[bin]]
name = "fr24d"
path = "src/main.rs"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size
lto = true
codegen-units = 1
