name: Publish Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-amd64:
    if: contains(github.event.head_commit.message, 'chore(publishing)')
    runs-on: ubuntu-26.04
    name: Build AMD64

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Rename binary
        run: mv target/release/fr24d fr24d-linux-amd64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: fr24d-amd64
          path: fr24d-linux-amd64

  build-arm64:
    if: contains(github.event.head_commit.message, 'chore(publishing)')
    runs-on: ubuntu-26.04-arm
    name: Build ARM64

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Rename binary
        run: mv target/release/fr24d fr24d-linux-arm64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: fr24d-arm64
          path: fr24d-linux-arm64

  publish:
    if: contains(github.event.head_commit.message, 'chore(publishing)')
    needs:
      - build-amd64
      - build-arm64

    runs-on: ubuntu-slim
    name: Publish GitHub Release

    steps:
      - name: Download AMD64 binary
        uses: actions/download-artifact@v4
        with:
          name: fr24d-amd64
          path: release

      - name: Download ARM64 binary
        uses: actions/download-artifact@v4
        with:
          name: fr24d-arm64
          path: release

      - name: Get SHA and file size of AMD64 binary
        id: amd64-info
        run: |
          sha256sum release/fr24d-linux-amd64 | awk '{print $1}' > release/fr24d-linux-amd64.sha256
          stat -c%s release/fr24d-linux-amd64 > release/fr24d-linux-amd64.size
          echo "amd64_sha=$(cat release/fr24d-linux-amd64.sha256)" >> "$GITHUB_OUTPUT"
          echo "amd64_size=$(cat release/fr24d-linux-amd64.size)" >> "$GITHUB_OUTPUT"

      - name: Get SHA and file size of ARM64 binary
        id: arm64-info
        run: |
          sha256sum release/fr24d-linux-arm64 | awk '{print $1}' > release/fr24d-linux-arm64.sha256
          stat -c%s release/fr24d-linux-arm64 > release/fr24d-linux-arm64.size
          echo "arm64_sha=$(cat release/fr24d-linux-arm64.sha256)" >> "$GITHUB_OUTPUT"
          echo "arm64_size=$(cat release/fr24d-linux-arm64.size)" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly ${{ github.run_number }}
          files: |
            release/fr24d-linux-amd64
            release/fr24d-linux-arm64